<h1>Liste des Produits </h1>

	<?php foreach ($this->entries as $entry): ?>

		<?php $id = $this->escape($entry->id)?>

		<div class="col-md-2 column productbox">
			<img href="" src="http://placehold.it/300x200/e67e22/ffffff&text=HTML5" class="img-responsive">
			<div class="producttitle" id=""><?php echo $this->escape($entry->productName) ?></div>
			<div class="productprice">
				<div class="pricetext">
					<?php echo $this->escape($entry->price)." Euros" ?>
				</div>
				<div class="pull-right">
					<?php echo'<a href="/appEcom/public/Cart/addtoCart/id/'.$id.'">Ajouter au panier</a>'; ?>
				</div>
			</div>

			<div class ="productdelete">
				<?php
					$_POST[$id] = $this->escape($entry->id);
					echo'<a href="/appEcom/public/Product/deleteProduct/id/'.$id.'">Supprimer le produit</a>';
				?>
			</div>
			<div class="productshow">
				<?php echo'<a href="/appEcom/public/Product/showProduct/id/'.$id.'">Afficher le produit</a>'; ?>
			</div>
		</div>
	<?php endforeach ?>




