<h1>Produit </h1>

    <?php $id = $this->id; ?>
    <div class="col-md-2 column productbox">
        <img src="http://placehold.it/300x200/e67e22/ffffff&text=HTML5" class="img-responsive">
        <div class="producttitle" id=""><?php echo $this->productName ?></div>
        <div class="productdescription"><?php echo $this->desc ?></div>
        <div class="productprice">
            <div class="quantityleft">
                Quantité disponible: <?php echo $this->quantity ?>
            </div>
            <div class="pricetext">
                <?php echo $this->price." Euros" ?>
            </div>
            <div class="pull-right">
                <a href="#" class="btn btn-danger btn-sm" role="button">Ajouter au panier</a>
            </div>
        </div>

        <div class ="productdelete">
            <?php
            echo'<a href="/appEcom/public/Product/deleteProduct/id/'.$id.'">Supprimer le produit</a>';
            ?>
        </div>
        <div class="productedit">
            <?php
            echo'<a href="/appEcom/public/Product/editProduct/id/'.$id.'">Editer le produit</a>';
            ?>
        </div>
    </div>





