<?php echo $this->doctype() ?>
<html>
    <head>
        <title>Site E-Commerce</title>
    </head>
    <body>
        <div>
            <div >
                <b>Site E-commerce</b>
            </div>
            <div >
                <a href="<?php echo $this->url(array('controller'=>'product'), 'default', true) ?>">Produits</a>
                <a href="<?php echo $this->url(array('controller'=>'cart'), 'default', true) ?>">Panier</a>
            </div>
        </div>

        <?php echo $this->layout()->content ?>

    </body>
</html>