<?php echo $this->doctype() ?>
<html>
    <head>
        <title>Site E-Commerce</title>
        <?php echo $this->headLink()->appendStylesheet('styles/styles.css') ?>
    </head>
    <body>
        <div>
            <div >
                <b>Site E-commerce</b>
            </div>
            <div >
                <a href="<?php echo $this->url(array('controller'=>'Product'), 'default', true) ?>">Produits</a>
                <a href="<?php echo $this->url(array('controller'=>'Cart'), 'default', true) ?>">Panier</a>
                <a href="<?php echo $this->url(array('controller'=>'Authent'), 'default', true) ?>">Login</a>
                <a href="<?php echo $this->url(array('controller'=>'Authent'), 'default', true) ?>">Logout</a>
            </div>
        </div>
        <div class="page-content">
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>