CREATE TABLE USER (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE

);

CREATE INDEX "id" ON "USER" ("id");


